MyApp.Client/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Shift;

namespace MyApp.Client.Controllers
{
    public class DashboardController : Controller
    {
        private static JobClient jobClient;
        private static JobServer jobServer;

        public DashboardController(IMemoryCache cache)
        {
            if (jobClient == null)
            {
                jobClient = cache.Get("Shift.JobClient") as JobClient;
            }
            if (jobServer == null)
            {
                jobServer = cache.Get("Shift.JobServer") as JobServer;
            }

        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ReadData(int? pageIndex, int? pageSize)
        {
            var jobViewList = await jobClient.GetJobViewsAsync(pageIndex, pageSize).ConfigureAwait(false);
            var output = new Dictionary<string, object>();
            output.Add("data", jobViewList.Items);
            output.Add("itemsCount", jobViewList.Total);

            return Json(output);
        }

        public async Task<IActionResult> Delete(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Delete jobs that's not running
            await jobClient.DeleteJobsAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> Reset(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Reset jobs that's not running
            await jobClient.ResetJobsAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        #region Shift Actions
        public async Task<IActionResult> Stop(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Set command to stop
            await jobClient.SetCommandStopAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> Pause(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Set command to stop
            await jobClient.SetCommandPauseAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> Continue(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Set command to stop
            await jobClient.SetCommandContinueAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> RunNow(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Set command to 'run-now', wait for RunServer to pickup and run it
            await jobClient.SetCommandRunNowAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> RunSelected(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            await jobServer.RunJobsAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> RunServer()
        {
            //Jobs running through this function will be running under the IIS Process!
            await jobServer.RunServerAsync().ConfigureAwait(false); //Run jobs server, use the MaxRunableJobs setting
            return Json(true);
        }

        public async Task<IActionResult> StopServer()
        {
            await jobServer.StopServerAsync().ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> CleanUp()
        {
            await jobServer.CleanUpAsync().ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> ProcessCmd()
        {
            await jobServer.PauseJobsAsync().ConfigureAwait(false);
            await jobServer.ContinueJobsAsync().ConfigureAwait(false);
            await jobServer.StopJobsAsync().ConfigureAwait(false);

            return Json(true);
        }
        #endregion
    }
}

MyApp.Client/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using MyApp.BusinessLayer;
using MyApp.DataLayer;
using Shift;
using Shift.Entities;

namespace MyApp.Client.Controllers
{
    public class JobController : Controller
    {
        private ShiftConfig _settings;
        private static JobClient jobClient;

        public JobController(IMemoryCache cache, IOptions<ShiftConfig> settings)
        {
            _settings = settings.Value;
            if (jobClient == null)
            {
                jobClient = cache.Get("Shift.JobClient") as JobClient;
            }
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Add(int? p1Count, int? p2Count, int? p3Count, int? p4Count, int? p5Count)
        {
            var appID = _settings.ApplicationID;
            if (string.IsNullOrWhiteSpace(appID))
                appID = "Shift.Demo.MVC.Core";

            var message = "";
            if (p1Count > 0)
            {
                for (var i = 0; i < p1Count; i++)
                {
                    var job1 = new Job1();
                    var progress = new SynchronousProgress<ProgressInfo>();
                    var cancelToken = (new CancellationTokenSource()).Token; //placeholder to be replaced by Server token
                    var pauseToken = (new PauseTokenSource()).Token;
                    await jobClient.AddAsync(appID, () => job1.Start("Hello World!", progress, cancelToken, pauseToken));
                }

                message += p1Count + " - Job1 added to queue. <br/>";
            }

            if (p2Count > 0)
            {
                for (var i = 0; i < p2Count; i++)
                {
                    var job2 = new Job2();
                    var progress = new SynchronousProgress<ProgressInfo>(); //just a place holder to be replaced by real Progress object from the server
                    var cancelToken = (new CancellationTokenSource()).Token; //placeholder to be replaced by Server token
                    var pauseToken = (new PauseTokenSource()).Token;
                    await jobClient.AddAsync(appID, () => job2.Start(progress, 1, cancelToken, pauseToken));
                }

                message += p2Count + " - Job2 added to queue. <br/>";
            }

            if (p3Count > 0)
            {
                var simpleList = new List<int>();
                for (var i = 1; i <= 100; i++)
                {
                    simpleList.Add(i);
                }

                for (var i = 0; i < p3Count; i++)
                {
                    var job3 = new Job3();
                    var progress = new SynchronousProgress<ProgressInfo>();
                    await jobClient.AddAsync(appID, () => job3.Start(progress, simpleList));
                }

                message += p3Count + " - Job3 added to queue. <br/>";
            }

            if (p4Count > 0)
            {
                var complexList = new List<TestData>();
                for (var i = 1; i <= 100; i++)
                {
                    var newData = new TestData();
                    newData.MyNumber = i;
                    newData.MyString = "mystring " + i;
                    complexList.Add(newData);
                }

                for (var i = 0; i < p4Count; i++)
                {
                    var job4 = new Job4();
                    var progress = new SynchronousProgress<ProgressInfo>();
                    var cancelToken = (new CancellationTokenSource()).Token; //placeholder to be replaced by Server token
                    var pauseToken = (new PauseTokenSource()).Token;
                    await jobClient.AddAsync(appID, () => job4.Start(progress, complexList, cancelToken, pauseToken));
                }

                message += p4Count + " - Job4 added to queue. <br/>";
            }

            if (p5Count > 0)
            {
                var simpleList = new List<int>();
                for (var i = 1; i <= 100; i++)
                {
                    simpleList.Add(i);
                }

                for (var i = 0; i < p5Count; i++)
                {
                    var job5 = new Job5();
                    var cancelToken = (new CancellationTokenSource()).Token; //placeholder to be replaced by Server token
                    var pauseToken = (new PauseTokenSource()).Token;
                    var progress = new SynchronousProgress<ProgressInfo>();
                    await jobClient.AddAsync(appID, () => job5.StartAsync(progress, simpleList, cancelToken, pauseToken));
                }

                message += p5Count + " - Job5 added to queue. <br/>";
            }

            ViewBag.Message = message;

            return View("Index");
        }


    }
}

MyApp.Client/Controllers/ProgressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Shift;

namespace MyApp.Client.Controllers
{
    public class ProgressController : Controller
    {
        private static JobClient jobClient;

        public ProgressController(IMemoryCache cache)
        {
            if (jobClient == null)
            {
                jobClient = cache.Get("Shift.JobClient") as JobClient;
            }
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ReadData(int? pageIndex, int? pageSize)
        {
            var jobViewList = await jobClient.GetJobViewsAsync(pageIndex, pageSize).ConfigureAwait(false);
            var output = new Dictionary<string, object>();
            output.Add("data", jobViewList.Items);
            output.Add("itemsCount", jobViewList.Total);

            return Json(output);
        }
    }
}

MyApp.Client/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shift.Demo.MVC.Core</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />

        <link rel="stylesheet" href="~/css/jsgrid.css" />
        <link rel="stylesheet" href="~/css/jsgrid-theme.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/css/jsgrid.min.css" />
        <link rel="stylesheet" href="~/css/jsgrid-theme.min.css" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MyApp.Client</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                    </li>
                    <li>
                        <a asp-controller="Progress" asp-action="Index">Status & Progress</a>
                    </li>
                    <li>
                        <a asp-controller="Job" asp-action="Index">Add Jobs</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/common.js" asp-append-version="true"></script>
        <script src="~/js/jsgrid.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/common.min.js" asp-append-version="true"></script>
        <script src="~/js/jsgrid.min.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>