MyApp.Client/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Shift;

namespace MyApp.Client.Controllers
{
    public class DashboardController : Controller
    {
        private static JobClient jobClient;
        private static JobServer jobServer;

        public DashboardController(IMemoryCache cache)
        {
            if (jobClient == null)
            {
                jobClient = cache.Get("Shift.JobClient") as JobClient;
            }
            if (jobServer == null)
            {
                jobServer = cache.Get("Shift.JobServer") as JobServer;
            }

        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ReadData(int? pageIndex, int? pageSize)
        {
            var jobViewList = await jobClient.GetJobViewsAsync(pageIndex, pageSize).ConfigureAwait(false);
            var output = new Dictionary<string, object>();
            output.Add("data", jobViewList.Items);
            output.Add("itemsCount", jobViewList.Total);

            return Json(output);
        }

        public async Task<IActionResult> Delete(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Delete jobs that's not running
            await jobClient.DeleteJobsAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> Reset(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Reset jobs that's not running
            await jobClient.ResetJobsAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        #region Shift Actions
        public async Task<IActionResult> Stop(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Set command to stop
            await jobClient.SetCommandStopAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> Pause(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Set command to stop
            await jobClient.SetCommandPauseAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> Continue(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Set command to stop
            await jobClient.SetCommandContinueAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> RunNow(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            //Set command to 'run-now', wait for RunServer to pickup and run it
            await jobClient.SetCommandRunNowAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> RunSelected(List<string> ids)
        {
            if (ids == null)
                return Json(false);

            await jobServer.RunJobsAsync(ids).ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> RunServer()
        {
            //Jobs running through this function will be running under the IIS Process!
            await jobServer.RunServerAsync().ConfigureAwait(false); //Run jobs server, use the MaxRunableJobs setting
            return Json(true);
        }

        public async Task<IActionResult> StopServer()
        {
            await jobServer.StopServerAsync().ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> CleanUp()
        {
            await jobServer.CleanUpAsync().ConfigureAwait(false);

            return Json(true);
        }

        public async Task<IActionResult> ProcessCmd()
        {
            await jobServer.PauseJobsAsync().ConfigureAwait(false);
            await jobServer.ContinueJobsAsync().ConfigureAwait(false);
            await jobServer.StopJobsAsync().ConfigureAwait(false);

            return Json(true);
        }
        #endregion
    }
}

MyApp.Client/Controllers/MethodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Options;
using Shift;

namespace MyApp.Client.Controllers
{
    [Route("[controller]")]
    public class MethodController : Controller
    {
        private static JobClient jobClient;

        public MethodController(IMemoryCache cache)
        {
            if (jobClient == null)
            {
                jobClient = cache.Get("Shift.JobClient") as JobClient;
            }
        }

        [Route("[action]/{jobID?}")]
        public async Task<IActionResult> Index(string jobID)
        {
            ViewBag.JobView = await jobClient.GetJobViewAsync(jobID);

            return View();
        }

    }
}

MyApp.Client/Controllers/RTProgressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using Shift;

namespace MyApp.Client.Controllers
{
    [Route("[controller]")]
    public class RTProgressController : Controller
    {
        private static JobClient jobClient;

        public RTProgressController(IMemoryCache cache)
        {
            if (jobClient == null)
            {
                jobClient = cache.Get("Shift.JobClient") as JobClient;
            }
        }

        [Route("[action]/{jobID?}")]
        public async Task<IActionResult> Index(string jobID)
        {
            ViewBag.JobID = jobID;
            return View();
        }

        [Route("[action]/{jobID?}")]
        public async Task<IActionResult> GetProgress(string jobID)
        {
            var jsProgress = await jobClient.GetProgressAsync(jobID).ConfigureAwait(false);

            return Json(jsProgress);
        }
    }
}

MyApp.Client/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
}
<h2>@ViewBag.Title</h2>

<div class="row">
    <div class="col-sm-7">
        <div class="command-bar btn-group-sm">
            <a href="#" class="btn btn-default" data-action="" data-key="refresh">Refresh</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("Reset", "Dashboard")" data-key="reset">Reset</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("Delete", "Dashboard")" data-key="delete">Delete</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("Stop", "Dashboard")" data-key="stop">Stop Cmd</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("Pause", "Dashboard")" data-key="pause">Pause Cmd</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("Continue", "Dashboard")" data-key="continue">Continue Cmd</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("RunNow", "Dashboard")" data-key="run-now">Run-Now Cmd</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("RunSelected", "Dashboard")" data-key="run-selected">Run Selected</a>
        </div>
    </div>

    <div class="col-sm-5">
        <div class="command-bar btn-group-sm pull-right">
            <a href="#" class="btn btn-default" data-action="@Url.Action("RunServer", "Dashboard")" data-key="run-server">Run Server</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("StopServer", "Dashboard")" data-key="stop-server">Stop Server</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("CleanUp", "Dashboard")" data-key="clean-up">Server Clean-Up</a>
            <a href="#" class="btn btn-default" data-action="@Url.Action("ProcessCmd", "Dashboard")" data-key="process-cmd">Process Cmd</a>
        </div>
    </div>
</div>

<div class="row" style="margin-top: 15px;">
    <div class="col-sm-12">
        <div id="grid"></div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
var readDataUrl = '@Url.Action("ReadData", "Dashboard")';
var methodUrl = '@Url.Action("Index", "Method")';
var rtProgressUrl = '@Url.Action("Index", "RTProgress")';

$(document).ready(function () {
    initializeGrid();
    initCommands();
});

function initializeGrid() {
    var dateField = function (config) {
        jsGrid.Field.call(this, config);
    };
    dateField.prototype = new jsGrid.Field({
        align: "center",
        sorter: function (date1, date2) {
            return new Date(date1) - new Date(date2);
        },
        itemTemplate: function (value) {
            if (value) {
                var date = new Date(value);
                return date.toLocaleDateString() + ' ' + date.toLocaleTimeString();
            } else {
                return;
            }
        }
    });
    jsGrid.fields.date = dateField;

    var longText = function (config) {
        jsGrid.Field.call(this, config);
    };
    longText.prototype = new jsGrid.Field({
        itemTemplate: function (value, item) {
            if (value)
                return '<div style="overflow-y: auto; max-height: 60px;">' + value + '</div>';
            else
                return;
        }
    });
    jsGrid.fields.longtext = longText;

    $("#grid").jsGrid({
        width: "100%",
        height: "auto",

        inserting: false,
        editing: false,
        sorting: false,

        paging: true,
        pageIndex: 1,
        pageSize: 20,
        pageLoading: true,
        pagerFormat: "{prev} {pages} {next}      {pageIndex} of {pageCount}",

        loadIndication: true,
        loadIndicationDelay: 500,
        loadMessage: "Please, wait...",
        loadShading: true,

        fields: [
            {
                name: "chkSelect", type: "checkbox", width: "25", title: "", align: "center",
                headerTemplate: function (value, item) {
                    return '<input type="checkbox" class="all-sel" />';
                },
                itemTemplate: function (value, item) {
                    return '<input type="checkbox" value="' + item.JobID + '" class="row-sel" />';
                }
            },
            {
                name: "JobID", type: "text", width: "60",
                itemTemplate: function (value, item) {
                    return '<div style="overflow-y: auto;"> <a href="' + rtProgressUrl + '/' + value + '" target="_blank">' + value + '</a></div>';
                }
            },
            { name: "AppID", type: "longtext", width: "70" },
            { name: "UserID", type: "text", width: "40", title: "UID", visible: false },
            { name: "ProcessID", type: "longtext", width: "70", title: "PID" },
            { name: "JobType", type: "text", width: "60", title: "Type", visible: false },
            {
                name: "JobName", type: "text", width: "60", title: "Name",
                itemTemplate: function (value, item) {
                    return '<a href="' + methodUrl + '/' + item.JobID + '" target="_blank">' + value + '</a>';
                }
            },
            { name: "InvokeMeta", type: "text", visible: false },
            { name: "Parameters", type: "text", visible: false },
            { name: "Status", type: "number", visible: false },
            { name: "Command", type: "text", width: "70" },
            { name: "StatusLabel", type: "text", width: "70", title: "Status" },
            { name: "Percent", type: "text", width: "50", title: "%" },
            { name: "Note", type: "longtext", width: "120" },
            { name: "Data", type: "longtext", width: "120" },
            { name: "Error", type: "longtext", width: "120" },
            { name: "Start", type: "date", width: "80" },
            { name: "End", type: "date", width: "80" },
            { name: "Created", type: "date", width: "80" }
        ],

        autoload: true,
        controller: {
            loadData: function (filter) {
                var d = $.Deferred();
                $.ajax({
                    cache: false,
                    type: "GET",
                    url: readDataUrl,
                    data: filter
                }).done(function (response) {
                    d.resolve(response);
                    return;
                });
                return d.promise();
            }
        }
    });
}

function initCommands() {
    $('#grid').on('click', 'input.all-sel', function () {
        var that = $(this);
        var checkboxes = that.closest('.jsgrid').find('input.row-sel')
        checkboxes.prop("checked", that.prop("checked"));
    });

    $('.command-bar a[data-key]').click(function () {
        var $this = $(this);
        var key = $this.attr('data-key');
        var action = $this.attr('data-action');
        var grid = $('#grid');
        var ids;
        switch (key) {
            case 'refresh':
                grid.jsGrid('render');
                break;
            case 'run-now':
            case 'stop':
            case 'pause':
            case 'continue':
                ids = getSelectedRecords('#grid');
                $.post(action, { "ids": ids }, function (result) {
                    grid.jsGrid('render');
                });
                break;
            case 'reset':
            case 'delete':
            case 'run-selected':
                ids = getSelectedRecords('#grid');
                if (confirm('Are you sure you want to ' + key.toUpperCase() + ' jobs?')) {
                    $.post(action, { "ids": ids }, function (result) {
                        grid.jsGrid('render');
                    });
                }
                break;
            case 'process-cmd':
                $.post(action, null, function (result) {
                    grid.jsGrid('render');
                });
                break;
            case 'clean-up':
                if (confirm('Are you sure you want to ' + key.toUpperCase() + ' jobs?')) {
                    $.post(action, null, function (result) {
                        grid.jsGrid('render');
                    });
                }
                break;
            case 'run-server':
                ids = getSelectedRecords('#grid');
                if (confirm('Are you sure you want to ' + key.toUpperCase() + '?')) {
                    $.post(action, null, function (result) {
                        grid.jsGrid('render');
                        alert('Shift Server is now running.');
                    });
                }
                break;
            case 'stop-server':
                ids = getSelectedRecords('#grid');
                if (confirm('Are you sure you want to ' + key.toUpperCase() + '?')) {
                    $.post(action, null, function (result) {
                        grid.jsGrid('render');
                        alert('Shift Server stopped.');
                    });
                }
                break;
        }
        return false;
    });

    function getSelectedRecords(divSel) {
        var selected = $(divSel + ' input.row-sel:checked');
        var ids = [];
        selected.each(function () {
            ids.push($(this).val());
        });

        return ids;
    }
}

    </script>
}